// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT1iWh59ialAdsTHW3bY54B4LGwjiZorY',
    appId: '1:750031802055:web:28ec988b9942bdbb07b8e2',
    messagingSenderId: '750031802055',
    projectId: 'reel-22a50',
    authDomain: 'reel-22a50.firebaseapp.com',
    storageBucket: 'reel-22a50.firebasestorage.app',
    measurementId: 'G-ZWEENK2JXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsMngoVY9XP7olOkfTpKwpr--Zdkj0laQ',
    appId: '1:750031802055:android:39b8eeed253bc11407b8e2',
    messagingSenderId: '750031802055',
    projectId: 'reel-22a50',
    storageBucket: 'reel-22a50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOfiBJYd9IXgfAPrypbGQis4Hm4hUBpf4',
    appId: '1:750031802055:ios:c6c99eefb1f8cf1e07b8e2',
    messagingSenderId: '750031802055',
    projectId: 'reel-22a50',
    storageBucket: 'reel-22a50.firebasestorage.app',
    iosBundleId: 'com.reel.reel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOfiBJYd9IXgfAPrypbGQis4Hm4hUBpf4',
    appId: '1:750031802055:ios:c6c99eefb1f8cf1e07b8e2',
    messagingSenderId: '750031802055',
    projectId: 'reel-22a50',
    storageBucket: 'reel-22a50.firebasestorage.app',
    iosBundleId: 'com.reel.reel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT1iWh59ialAdsTHW3bY54B4LGwjiZorY',
    appId: '1:750031802055:web:0ffe41ddb7f9693f07b8e2',
    messagingSenderId: '750031802055',
    projectId: 'reel-22a50',
    authDomain: 'reel-22a50.firebaseapp.com',
    storageBucket: 'reel-22a50.firebasestorage.app',
    measurementId: 'G-CQ8CCMBLJM',
  );
}
